[package]
name = "outref"
version = "0.3.0"
edition = "2021"
description = "A write-only reference"
license = "MIT"
repository = "https://github.com/Nugine/outref"
keywords = ["write-only", "reference", "slice"]
categories = ["no-std", "rust-patterns"]
rust-version = "1.63.0"
