[package]
name = "outref"
version = "0.1.0"
edition = "2021"
description = "Write-only references and slices"
license = "MIT"
repository = "https://github.com/Nugine/outref"
keywords = ["write-only", "reference", "slice"]
categories = ["no-std", "rust-patterns"]
rust-version = "1.62.1"
