on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy, miri
      - run: |
          cargo fmt --all -- --check
      - run: |
          cargo clippy -- -D warnings
      - run: |
          cargo test
      - run: |
          cargo miri test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: 
          - stable
          - nightly
          - 1.63.0 # MSRV
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: |
          cargo test
